server:
  port: 8088

spring:
  security:
    oauth2:
      client:
        registration:
#          facebook:
#            client-id: 3847596678663991
#            client-secret: 457b63fc966846bd06b3d3fc30674d4d
          google:
            client-id: 588833977624-isg6dfaohn04fcn8e2qoa0sg3ifmk1ac.apps.googleusercontent.com
            client-secret: g8n9yqkZUj8_4_OcI-qblr2s


